### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by runjsrun** [njj/haversine#13]
Do you have a test suite?

**Comment by runjsrun** [comment]
@njj I was looking for a travis CI badge in the readme and didn't find one.  Have you considered using a CI service?

**Comment by njj** [comment]
@runjsrun Yeah it's definitely something I could do, but generally this project is pretty stagnant and doesn't have much in the way of PRs or regular new features.  So the usage of a CI might be a bit of an overkill for such a small library.
