### ISSUE TITLE
Standard project files

### ISSUE THREAD

**Issue by RinkAttendant6** [njj/haversine#18]
## Keep a changelog

I see that an update was released a few hours ago but there is no changelog. Not sure if you haven't had a chance to write one yet, if so then please disregard this.

Some tips here: http://keepachangelog.com/en/1.0.0/ ...doesn't need to be very elaborate, even basic descriptions of the changes should suffice. If you don't want to commit a separate file then at least documenting them in the GitHub releases would be helpful.

## License

Another thing that I noticed was the lack of license file (apart from the "MIT License" link at the bottom of the readme). I suggest adding one so that people browsing the repo on GitHub can quickly identify the license of the project (more info here: https://github.com/blog/2252-license-now-displayed-on-repository-overview)

Great package by the way, I use it along with the HTML5 Geolocation API for a small feature in an application I develop at work.

**Comment by njj** [comment]
@RinkAttendant6 Thanks for the advice!  I will do my best to update the changelog better.
