### ISSUE TITLE
Question: are this formulae correct?

### ISSUE THREAD

**Issue by itpmngt** [njj/haversine#30]
So we have 
`var a = Math.sin(dLat/2) * Math.sin(dLat/2) +`

that is the same as `Math.sin(dLat/2) * 2 +`, so what is the point of calculating twice?

**Comment by officiallyemma** [comment]
`x * x` is actually `x^2` not `x*2` but your point is very valid. Two calls to Math.sin() could be simplified to one like so:

```Javascript
let z = Math.sin(dLat/2)
var a = z * z + .....
```

I'm curious to see what other optimizations could be made, and their impact on runtime.

edit: I ran some tests and it seems like this library is very fast, so I don't see runtime as a problem.
